['Traceback (most recent call last):\n',
 '  File "C:\\Python39\\lib\\site-packages\\discord\\ext\\commands\\bot.py", '
 'line 618, in _load_from_module_spec\n'
 '    setup(self)\n',
 '  File "c:\\Users\\cutie\\Desktop\\tragedy\\Cogs\\secret\\captcha.py", line '
 '91, in setup\n'
 '    bot.add_cog(Captcha(bot))\n',
 '  File "c:\\Users\\cutie\\Desktop\\tragedy\\Cogs\\secret\\captcha.py", line '
 '34, in __init__\n'
 '    self.chars = tragedy.randomString(5)\n',
 '  File "c:\\Users\\cutie\\Desktop\\tragedy\\resources\\utilities.py", line '
 '80, in randomString\n'
 "    randString = ''.join(random.choice(components) in range(length))\n",
 'TypeError: can only join an iterable\n',
 '\nThe above exception was the direct cause of the following exception:\n\n',
 'Traceback (most recent call last):\n',
 '  File "c:\\Users\\cutie\\Desktop\\tragedy\\loader.py", line 39, in '
 '<module>\n'
 '    bot.load_extension("Cogs.{}.{}".format(subdir.replace(\'/\', \'.\'), '
 'filename[:-3]))\n',
 '  File "C:\\Python39\\lib\\site-packages\\discord\\ext\\commands\\bot.py", '
 'line 678, in load_extension\n'
 '    self._load_from_module_spec(spec, name)\n',
 '  File "C:\\Python39\\lib\\site-packages\\discord\\ext\\commands\\bot.py", '
 'line 623, in _load_from_module_spec\n'
 '    raise errors.ExtensionFailed(key, e) from e\n',
 "discord.ext.commands.errors.ExtensionFailed: Extension 'Cogs.secret.captcha' "
 'raised an error: TypeError: can only join an iterable\n']
